
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using  NFramework.ModuleSystem;


namespace NFramework.Game.ConfigReader
{
public partial class TbBricksMap : IConfig<global::NFramework.Game.TableBricksMap>
{
    private System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableBricksMap> _dataMap;
    private System.Collections.Generic.List<global::NFramework.Game.TableBricksMap> _dataList;

    public void LoadData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableBricksMap>(n);
        _dataList = new System.Collections.Generic.List<global::NFramework.Game.TableBricksMap>(n);
        for (int i = n; i > 0; --i)
        {
            global::NFramework.Game.TableBricksMap _v;
            _v = global::NFramework.Game.TableBricksMap.DeserializeTableBricksMap(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public static TbBricksMap Create() => new TbBricksMap();

    // IConfig<T>
    public global::NFramework.Game.TableBricksMap Get(int id) => _dataMap[id];
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableBricksMap> GetAll() => _dataMap;
    public System.Collections.IDictionary GetDic() => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableBricksMap> GetList() => _dataList;
    public global::NFramework.Game.TableBricksMap GetBean() => throw new System.NotSupportedException("TbBricksMap is a map table, use Get(id).");

    // Convenience helpers
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableBricksMap> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableBricksMap> DataList => _dataList;
    public global::NFramework.Game.TableBricksMap GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public global::NFramework.Game.TableBricksMap this[int key] => _dataMap[key];

    public void ResolveRef(TablesReader tables) { }

}

}

