
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using  NFramework.ModuleSystem;


namespace NFramework.Game.ConfigReader
{
public partial class TbMapLevelConfig : IConfig<global::NFramework.Game.TableMapLevelConfig>
{
    private System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableMapLevelConfig> _dataMap;
    private System.Collections.Generic.List<global::NFramework.Game.TableMapLevelConfig> _dataList;

    public void LoadData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableMapLevelConfig>(n);
        _dataList = new System.Collections.Generic.List<global::NFramework.Game.TableMapLevelConfig>(n);
        for (int i = n; i > 0; --i)
        {
            global::NFramework.Game.TableMapLevelConfig _v;
            _v = global::NFramework.Game.TableMapLevelConfig.DeserializeTableMapLevelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public static TbMapLevelConfig Create() => new TbMapLevelConfig();

    // IConfig<T>
    public global::NFramework.Game.TableMapLevelConfig Get(int id) => _dataMap[id];
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableMapLevelConfig> GetAll() => _dataMap;
    public System.Collections.IDictionary GetDic() => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableMapLevelConfig> GetList() => _dataList;
    public global::NFramework.Game.TableMapLevelConfig GetBean() => throw new System.NotSupportedException("TbMapLevelConfig is a map table, use Get(id).");

    // Convenience helpers
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableMapLevelConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableMapLevelConfig> DataList => _dataList;
    public global::NFramework.Game.TableMapLevelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public global::NFramework.Game.TableMapLevelConfig this[int key] => _dataMap[key];

    public void ResolveRef(TablesReader tables) { }

}

}

