
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using  NFramework.ModuleSystem;


namespace NFramework.Game.ConfigReader
{
public partial class TbRole : IConfig<global::NFramework.Game.TableRole>
{
    private System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableRole> _dataMap;
    private System.Collections.Generic.List<global::NFramework.Game.TableRole> _dataList;

    public void LoadData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableRole>(n);
        _dataList = new System.Collections.Generic.List<global::NFramework.Game.TableRole>(n);
        for (int i = n; i > 0; --i)
        {
            global::NFramework.Game.TableRole _v;
            _v = global::NFramework.Game.TableRole.DeserializeTableRole(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public static TbRole Create() => new TbRole();

    // IConfig<T>
    public global::NFramework.Game.TableRole Get(int id) => _dataMap[id];
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableRole> GetAll() => _dataMap;
    public System.Collections.IDictionary GetDic() => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableRole> GetList() => _dataList;
    public global::NFramework.Game.TableRole GetBean() => throw new System.NotSupportedException("TbRole is a map table, use Get(id).");

    // Convenience helpers
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableRole> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableRole> DataList => _dataList;
    public global::NFramework.Game.TableRole GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public global::NFramework.Game.TableRole this[int key] => _dataMap[key];

    public void ResolveRef(TablesReader tables) { }

}

}

