
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using  NFramework.ModuleSystem;


namespace NFramework.Game.ConfigReader
{
public partial class TbSlotConfig : IConfig<global::NFramework.Game.TableSlotConfig>
{
    private System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableSlotConfig> _dataMap;
    private System.Collections.Generic.List<global::NFramework.Game.TableSlotConfig> _dataList;

    public void LoadData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableSlotConfig>(n);
        _dataList = new System.Collections.Generic.List<global::NFramework.Game.TableSlotConfig>(n);
        for (int i = n; i > 0; --i)
        {
            global::NFramework.Game.TableSlotConfig _v;
            _v = global::NFramework.Game.TableSlotConfig.DeserializeTableSlotConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public static TbSlotConfig Create() => new TbSlotConfig();

    // IConfig<T>
    public global::NFramework.Game.TableSlotConfig Get(int id) => _dataMap[id];
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableSlotConfig> GetAll() => _dataMap;
    public System.Collections.IDictionary GetDic() => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableSlotConfig> GetList() => _dataList;
    public global::NFramework.Game.TableSlotConfig GetBean() => throw new System.NotSupportedException("TbSlotConfig is a map table, use Get(id).");

    // Convenience helpers
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableSlotConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableSlotConfig> DataList => _dataList;
    public global::NFramework.Game.TableSlotConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public global::NFramework.Game.TableSlotConfig this[int key] => _dataMap[key];

    public void ResolveRef(TablesReader tables) { }

}

}

