using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

using XHFramework;
namespace NFramework.ModuleSystem
{
    /// <summary>
    /// UIFacade 脚本生成：输出到 <see cref="UISystemConfig.LogicScriptGenerateRootPath"/> / 模块名 / 脚本名.cs；
    /// 已存在文件时只替换「UI Components (Auto Generated)」区域（属性 + OnBindFacade），保留 Event Handlers / Live 等手写代码。
    /// 组件属性由 Default/Types 下 ComponentProperty 模板生成；绑定与事件桩由
    /// <see cref="UIFacadeCodeTemplateLoader.InteractTemplateIdByComponentTypeName"/> 映射到
    /// <c>InteractTemplates/*.txt</c>（<<<Bind>>> / <<<Event>>>）。
    /// </summary>
    public static class UIFacadeScriptGenerator
    {
        private const string AutoGenRegionMarker = "#region UI Components (Auto Generated)";

        private readonly struct ButtonGenInfo
        {
            public readonly string FieldName;
            public readonly string TypeShortName;
            public readonly string TypeFullName;
            public readonly int ElementIndex;
            public readonly string InteractTemplateId;

            public ButtonGenInfo(string fieldName, string typeShortName, string typeFullName, int elementIndex, string interactTemplateId)
            {
                FieldName = fieldName;
                TypeShortName = typeShortName;
                TypeFullName = typeFullName;
                ElementIndex = elementIndex;
                InteractTemplateId = interactTemplateId;
            }
        }

        public static void GenerateScript(UIFacade facade)
        {
            if (facade == null || string.IsNullOrEmpty(facade.m_ScriptName))
            {
                EditorUtility.DisplayDialog("错误", "脚本名称不能为空，请先配置基本信息", "确定");
                return;
            }

            string scriptName = facade.m_ScriptName;
            string moduleFolder = facade.m_ModuleName ?? "";

            ViewConfig viewConfig = UIConfigUtilsEditor.GetViewConfig(facade);
            bool isWindow = viewConfig != null && viewConfig.IsWindow;

            UIFacadeViewConfigDrawer.SaveViewConfigToJson(facade, viewConfig);

            string logicAssetPath = Path.Combine(FrameworkConfigAssetEditor.GetConfig().UISystemConfig.LogicScriptGenerateRootPath, moduleFolder, scriptName + ".cs")
                .Replace('\\', '/');
            string logicDiskPath = AssetPathToAbsolute(logicAssetPath);

            string logicDir = Path.GetDirectoryName(logicDiskPath);
            if (!string.IsNullOrEmpty(logicDir) && !Directory.Exists(logicDir))
                Directory.CreateDirectory(logicDir);

            if (!WriteLogicFile(logicDiskPath, logicAssetPath, scriptName, facade, isWindow))
                return;

            AssetDatabase.ImportAsset(logicAssetPath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();

            EditorUtility.DisplayDialog("成功", $"脚本生成完毕！\n\n{logicAssetPath}", "确定");
        }

        private static string AssetPathToAbsolute(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath))
                return assetPath;
            assetPath = assetPath.Replace('\\', '/');
            const string assetsPrefix = "Assets/";
            if (assetPath.StartsWith(assetsPrefix, System.StringComparison.OrdinalIgnoreCase))
            {
                string underAssets = assetPath.Substring(assetsPrefix.Length).Replace('/', Path.DirectorySeparatorChar);
                return Path.Combine(Application.dataPath, underAssets);
            }

            return Path.GetFullPath(assetPath);
        }

        /// <returns>是否成功写入（模板缺失时为 false）。</returns>
        private static bool WriteLogicFile(
            string diskPath,
            string assetPath,
            string scriptName,
            UIFacade facade,
            bool isWindow)
        {
            string baseClass = isWindow ? "Window" : "View";

            if (!TryBuildPropertiesAndBind(facade, out string propertiesCode, out string bindClicksCode,
                    out List<ButtonGenInfo> buttonInfos, out Dictionary<string, (string bindRaw, string eventRaw)> interactRawById,
                    out string buildError))
            {
                EditorUtility.DisplayDialog("错误", buildError, "确定");
                return false;
            }

            string newAutoGenRegion = BuildAutoGeneratedRegion(propertiesCode, bindClicksCode);

            if (File.Exists(diskPath))
            {
                string existing = File.ReadAllText(diskPath, Encoding.UTF8);
                if (TryReplaceAutoGeneratedRegion(existing, newAutoGenRegion, out string patched))
                {
                    File.WriteAllText(diskPath, patched, new UTF8Encoding(false));
                    return true;
                }

                EditorUtility.DisplayDialog(
                    "提示",
                    $"未在文件中找到区域 \"{AutoGenRegionMarker}\"，将按完整模板覆盖写入：\n{assetPath}",
                    "确定");
            }

            string shell = UIFacadeCodeTemplateLoader.LoadClassShellTemplate();
            if (string.IsNullOrEmpty(shell))
            {
                EditorUtility.DisplayDialog("错误",
                    "找不到 UIFacade 类壳模板。请确认存在：\n" + FrameworkConfigAssetEditor.GetConfig().UISystemConfig.UIFacadeClassShellTemplatePath +
                    "\n或旧路径 Template/UIFacadeTemplate.txt", "确定");
                return false;
            }

            if (!TryBuildEventHandlersStubs(buttonInfos, interactRawById, out string eventHandlersCode, out string stubError))
            {
                EditorUtility.DisplayDialog("错误", stubError, "确定");
                return false;
            }

            string namespaceStr = "Game.Logic";
            string code = shell
                .Replace("{{Namespace}}", namespaceStr)
                .Replace("{{ScriptName}}", scriptName)
                .Replace("{{BaseClass}}", baseClass)
                .Replace("{{Properties}}", propertiesCode)
                .Replace("{{BindClicks}}", bindClicksCode)
                .Replace("{{EventHandlers}}", eventHandlersCode);

            File.WriteAllText(diskPath, code, new UTF8Encoding(false));
            return true;
        }

        private static bool TryBuildPropertiesAndBind(
            UIFacade facade,
            out string propertiesCode,
            out string bindClicksCode,
            out List<ButtonGenInfo> buttonInfos,
            out Dictionary<string, (string bindRaw, string eventRaw)> interactRawById,
            out string error)
        {
            propertiesCode = "";
            bindClicksCode = "";
            buttonInfos = new List<ButtonGenInfo>();
            interactRawById = new Dictionary<string, (string bindRaw, string eventRaw)>();
            error = null;

            var propertiesSb = new StringBuilder();
            var bindSb = new StringBuilder();

            if (facade.m_UIElements != null)
            {
                for (int i = 0; i < facade.m_UIElements.Count; i++)
                {
                    UIFacade.UIElement uiItem = facade.m_UIElements[i];
                    if (uiItem == null || uiItem.Component == null || string.IsNullOrEmpty(uiItem.Name))
                        continue;

                    System.Type ct = uiItem.Component.GetType();
                    string typeFullName = ct.FullName ?? ct.Name;
                    string typeShortName = ct.Name;

                    string propTpl = UIFacadeCodeTemplateLoader.LoadSnippet(typeShortName,
                        UIFacadeCodeTemplateLoader.ComponentPropertyFile);
                    if (propTpl == null)
                    {
                        error = $"缺少组件属性模板 {UIFacadeCodeTemplateLoader.ComponentPropertyFile}\n路径: {FrameworkConfigAssetEditor.GetConfig().UISystemConfig.UIFacadeCodeTemplatesRoot}/Types/{typeShortName}/ 或 Default/";
                        return false;
                    }

                    string propBlock = UIFacadeCodeTemplateLoader.ApplyVariables(propTpl,
                        ("TypeFullName", typeFullName),
                        ("TypeShortName", typeShortName),
                        ("FieldName", uiItem.Name),
                        ("Index", i.ToString()));
                    AppendSnippetBlock(propertiesSb, propBlock);

                    if (!UIFacadeCodeTemplateLoader.TryGetInteractTemplateId(typeShortName, typeFullName, out string templateId))
                        continue;

                    if (!interactRawById.TryGetValue(templateId, out (string bindRaw, string eventRaw) rawPair))
                    {
                        if (!UIFacadeCodeTemplateLoader.TryLoadInteractTemplate(templateId, out string br, out string er, out string loadErr))
                        {
                            error = loadErr;
                            return false;
                        }

                        rawPair = (br, er);
                        interactRawById[templateId] = rawPair;
                    }

                    string clickMethodName = "On" + uiItem.Name + "Click";
                    string bindBlock = UIFacadeCodeTemplateLoader.ApplyVariables(rawPair.bindRaw,
                        ("TypeFullName", typeFullName),
                        ("TypeShortName", typeShortName),
                        ("FieldName", uiItem.Name),
                        ("Index", i.ToString()),
                        ("ClickMethodName", clickMethodName));
                    AppendSnippetBlock(bindSb, bindBlock);

                    buttonInfos.Add(new ButtonGenInfo(uiItem.Name, typeShortName, typeFullName, i, templateId));
                }
            }

            propertiesCode = propertiesSb.ToString();
            bindClicksCode = bindSb.ToString();
            return true;
        }

        private static bool TryBuildEventHandlersStubs(
            List<ButtonGenInfo> buttonInfos,
            Dictionary<string, (string bindRaw, string eventRaw)> interactRawById,
            out string eventHandlersCode,
            out string error)
        {
            eventHandlersCode = "";
            error = null;
            var sb = new StringBuilder();

            foreach (ButtonGenInfo btn in buttonInfos)
            {
                if (interactRawById == null || !interactRawById.TryGetValue(btn.InteractTemplateId, out (string bindRaw, string eventRaw) raw))
                {
                    error = "内部错误：缺少交互模板缓存 \"" + btn.InteractTemplateId + "\"。";
                    return false;
                }

                string clickMethodName = "On" + btn.FieldName + "Click";
                string block = UIFacadeCodeTemplateLoader.ApplyVariables(raw.eventRaw,
                    ("TypeFullName", btn.TypeFullName),
                    ("TypeShortName", btn.TypeShortName),
                    ("FieldName", btn.FieldName),
                    ("Index", btn.ElementIndex.ToString()),
                    ("ClickMethodName", clickMethodName));
                AppendSnippetBlock(sb, block);
            }

            eventHandlersCode = sb.ToString();
            return true;
        }

        /// <summary>保证片段末尾有换行，便于多块拼接。</summary>
        private static void AppendSnippetBlock(StringBuilder sb, string block)
        {
            if (string.IsNullOrEmpty(block))
                return;

            sb.Append(block);
            if (sb.Length > 0 && sb[sb.Length - 1] != '\n')
                sb.AppendLine();
        }

        private static string BuildAutoGeneratedRegion(string propertiesCode, string bindClicksCode)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        #region UI Components (Auto Generated)");
            if (!string.IsNullOrEmpty(propertiesCode))
                sb.Append(propertiesCode);
            sb.AppendLine("        protected override void OnBindFacade()");
            sb.AppendLine("        {");
            if (!string.IsNullOrEmpty(bindClicksCode))
                sb.Append(bindClicksCode);
            sb.AppendLine("        }");
            sb.AppendLine("        #endregion");
            return sb.ToString();
        }

        private static bool TryReplaceAutoGeneratedRegion(string fileContent, string newRegionBlock, out string updated)
        {
            updated = null;
            int start = fileContent.IndexOf(AutoGenRegionMarker, System.StringComparison.Ordinal);
            if (start < 0)
                return false;

            int regionLineStart = GetLineStartIndex(fileContent, start);

            int searchPos = start + AutoGenRegionMarker.Length;
            int depth = 1;
            int i = searchPos;
            while (i < fileContent.Length && depth > 0)
            {
                int nextRegion = fileContent.IndexOf("#region", i, System.StringComparison.Ordinal);
                int nextEnd = fileContent.IndexOf("#endregion", i, System.StringComparison.Ordinal);
                if (nextEnd < 0)
                    return false;

                if (nextRegion >= 0 && nextRegion < nextEnd)
                {
                    depth++;
                    i = nextRegion + "#region".Length;
                }
                else
                {
                    depth--;
                    if (depth == 0)
                    {
                        int endLineAfterEndRegion = GetLineEndExclusive(fileContent, nextEnd);
                        string before = fileContent.Substring(0, regionLineStart);
                        string after = fileContent.Substring(endLineAfterEndRegion);
                        updated = before + newRegionBlock + after;
                        return true;
                    }

                    i = nextEnd + "#endregion".Length;
                }
            }

            return false;
        }

        private static int GetLineStartIndex(string content, int indexInLine)
        {
            int nl = content.LastIndexOf('\n', indexInLine);
            if (nl < 0)
                return 0;
            return nl + 1;
        }

        private static int GetLineEndExclusive(string content, int indexFrom)
        {
            int nl = content.IndexOf('\n', indexFrom);
            if (nl < 0)
                return content.Length;
            return nl + 1;
        }
    }
}
