using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

using NFramework;
namespace NFramework.ModuleSystem
{
    /// <summary>
    /// UIFacade 脚本生成：输出到 <see cref="UISystemConfig.LogicScriptGenerateRootPath"/> / 模块名 / UI / 脚本名.cs；
    /// 已存在文件时只替换「UI Components (Auto Generated)」区域（属性 + OnBindFacade），保留 Event Handlers / Live 等手写代码。
    /// 不会整文件覆盖已存在的类：找不到自动区域时优先向已有类中插入自动区域，无法安全插入则中止并提示，避免误删手写代码。
    /// 组件属性由 Default/Types 下 ComponentProperty 模板生成；绑定与事件桩由
    /// <see cref="UIFacadeCodeTemplateLoader.InteractTemplateIdByComponentTypeName"/> 映射到
    /// <c>InteractTemplates/*.txt</c>（<<<Bind>>> / <<<Event>>>）。
    /// </summary>
    public static class UIFacadeScriptGenerator
    {
        private const string AutoGenRegionMarker = "#region UI Components (Auto Generated)";

        private readonly struct ButtonGenInfo
        {
            public readonly string FieldName;
            public readonly string TypeShortName;
            public readonly string TypeFullName;
            public readonly int ElementIndex;
            public readonly string InteractTemplateId;

            public ButtonGenInfo(string fieldName, string typeShortName, string typeFullName, int elementIndex, string interactTemplateId)
            {
                FieldName = fieldName;
                TypeShortName = typeShortName;
                TypeFullName = typeFullName;
                ElementIndex = elementIndex;
                InteractTemplateId = interactTemplateId;
            }
        }

        public static void GenerateScript(UIFacade facade)
        {
            if (facade == null || string.IsNullOrEmpty(facade.m_ScriptName))
            {
                EditorUtility.DisplayDialog("错误", "脚本名称不能为空，请先配置基本信息", "确定");
                return;
            }

            string scriptName = facade.m_ScriptName;
            string moduleFolder = facade.m_ModuleName ?? "";

            ViewConfig viewConfig = UIConfigUtilsEditor.GetViewConfig(facade);
            bool isWindow = viewConfig != null && viewConfig.IsWindow;

            UIFacadeViewConfigDrawer.SaveViewConfigToJson(facade, viewConfig);

            string logicAssetPath = Path.Combine(FrameworkConfigAssetEditor.GetConfig().UISystemConfig.LogicScriptGenerateRootPath, moduleFolder, "UI", scriptName + ".cs")
                .Replace('\\', '/');
            string logicDiskPath = AssetPathToAbsolute(logicAssetPath);

            string logicDir = Path.GetDirectoryName(logicDiskPath);
            if (!string.IsNullOrEmpty(logicDir) && !Directory.Exists(logicDir))
                Directory.CreateDirectory(logicDir);

            if (!WriteLogicFile(logicDiskPath, logicAssetPath, scriptName, facade, isWindow))
                return;

            AssetDatabase.ImportAsset(logicAssetPath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();

            Debug.Log($"[UIFacade] 脚本生成完毕: {logicAssetPath}");
        }

        private static string AssetPathToAbsolute(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath))
                return assetPath;
            assetPath = assetPath.Replace('\\', '/');
            const string assetsPrefix = "Assets/";
            if (assetPath.StartsWith(assetsPrefix, System.StringComparison.OrdinalIgnoreCase))
            {
                string underAssets = assetPath.Substring(assetsPrefix.Length).Replace('/', Path.DirectorySeparatorChar);
                return Path.Combine(Application.dataPath, underAssets);
            }

            return Path.GetFullPath(assetPath);
        }

        /// <returns>是否成功写入（模板缺失时为 false）。</returns>
        private static bool WriteLogicFile(
            string diskPath,
            string assetPath,
            string scriptName,
            UIFacade facade,
            bool isWindow)
        {
            string baseClass = isWindow ? "Window" : "View";

            if (!TryBuildPropertiesAndBind(facade, out string propertiesCode, out string listFieldsCode, out string bindClicksCode,
                    out List<ButtonGenInfo> buttonInfos, out Dictionary<string, (string bindRaw, string eventRaw)> interactRawById,
                    out string buildError))
            {
                EditorUtility.DisplayDialog("错误", buildError, "确定");
                return false;
            }

            string newAutoGenRegion = BuildAutoGeneratedRegion(propertiesCode, listFieldsCode, bindClicksCode);

            if (File.Exists(diskPath))
            {
                string existing = File.ReadAllText(diskPath, Encoding.UTF8);
                if (TryReplaceAutoGeneratedRegion(existing, newAutoGenRegion, out string patched))
                {
                    File.WriteAllText(diskPath, patched, new UTF8Encoding(false));
                    return true;
                }

                // 已有文件且没有自动区域：不再整文件覆盖。
                // 只有能证明文件是“手写类且没有生成过 Facade 成员”时，才向类内插入自动区域；
                // 否则中止，避免重复定义或丢失手写逻辑。
                if (!existing.Contains("OnBindFacade") && !existing.Contains("Facade.Components["))
                {
                    if (TryInsertAutoGeneratedRegion(existing, scriptName, baseClass, newAutoGenRegion, out string inserted))
                    {
                        File.WriteAllText(diskPath, inserted, new UTF8Encoding(false));
                        return true;
                    }
                }

                EditorUtility.DisplayDialog(
                    "未覆盖已有代码",
                    $"文件已存在且未找到自动生成区域，已停止写入：\n{assetPath}\n\n" +
                    "为避免覆盖手写逻辑，请任选一种处理：\n" +
                    "1) 在类中保留标准区域 #region UI Components (Auto Generated) ... #endregion；\n" +
                    "2) 把自动成员迁移到一个独立 partial 文件；\n" +
                    "3) 手动删除后重新生成（会丢失自定义代码，需自行备份）。",
                    "确定");
                return false;
            }

            string shell = UIFacadeCodeTemplateLoader.LoadClassShellTemplate();
            if (string.IsNullOrEmpty(shell))
            {
                EditorUtility.DisplayDialog("错误",
                    "找不到 UIFacade 类壳模板。请确认存在：\n" + FrameworkConfigAssetEditor.GetConfig().UISystemConfig.UIFacadeClassShellTemplatePath +
                    "\n或旧路径 Template/UIFacadeTemplate.txt", "确定");
                return false;
            }

            if (!TryBuildEventHandlersStubs(buttonInfos, interactRawById, out string eventHandlersCode, out string stubError))
            {
                EditorUtility.DisplayDialog("错误", stubError, "确定");
                return false;
            }

            string namespaceStr = "Game.Logic";
            string code = shell
                .Replace("{{Namespace}}", namespaceStr)
                .Replace("{{ScriptName}}", scriptName)
                .Replace("{{BaseClass}}", baseClass)
                .Replace("{{Properties}}", propertiesCode)
                .Replace("{{BindClicks}}", bindClicksCode)
                .Replace("{{EventHandlers}}", eventHandlersCode);

            File.WriteAllText(diskPath, code, new UTF8Encoding(false));
            return true;
        }

        private static bool TryBuildPropertiesAndBind(
            UIFacade facade,
            out string propertiesCode,
            out string listFieldsCode,
            out string bindClicksCode,
            out List<ButtonGenInfo> buttonInfos,
            out Dictionary<string, (string bindRaw, string eventRaw)> interactRawById,
            out string error)
        {
            propertiesCode = "";
            listFieldsCode = "";
            bindClicksCode = "";
            buttonInfos = new List<ButtonGenInfo>();
            interactRawById = new Dictionary<string, (string bindRaw, string eventRaw)>();
            error = null;

            var propertiesSb = new StringBuilder();
            var listFieldsSb = new StringBuilder();
            var bindSb = new StringBuilder();

            // 已声明列表对象的 GameObject，避免同一物体上多个元素重复声明
            var listFieldObjects = new HashSet<GameObject>();

            if (facade.m_UIElements != null)
            {
                for (int i = 0; i < facade.m_UIElements.Count; i++)
                {
                    UIFacade.UIElement uiItem = facade.m_UIElements[i];
                    if (uiItem == null || uiItem.Component == null || string.IsNullOrEmpty(uiItem.Name))
                        continue;

                    System.Type ct = uiItem.Component.GetType();
                    string typeFullName = ct.FullName ?? ct.Name;
                    string typeShortName = ct.Name;

                    string propTpl = UIFacadeCodeTemplateLoader.LoadSnippet(typeShortName,
                        UIFacadeCodeTemplateLoader.ComponentPropertyFile);
                    if (propTpl == null)
                    {
                        error = $"缺少组件属性模板 {UIFacadeCodeTemplateLoader.ComponentPropertyFile}\n路径: {FrameworkConfigAssetEditor.GetConfig().UISystemConfig.UIFacadeCodeTemplatesRoot}/Types/{typeShortName}/ 或 Default/";
                        return false;
                    }

                    string propBlock = UIFacadeCodeTemplateLoader.ApplyVariables(propTpl,
                        ("TypeFullName", typeFullName),
                        ("TypeShortName", typeShortName),
                        ("FieldName", uiItem.Name),
                        ("Index", i.ToString()));
                    AppendSnippetBlock(propertiesSb, propBlock);

                    // 列表组件：自动声明对应的列表对象
                    // LoopScrollRect 系列 → LoopListViewComponent；UGUI ScrollRect → SimpleListViewComponent
                    if (uiItem.Component is Component comp && comp != null && comp.gameObject != null &&
                        listFieldObjects.Add(comp.gameObject))
                    {
                        string listType = null;
                        if (comp.gameObject.GetComponent<LoopScrollRectBase>() != null)
                        {
                            listType = "LoopListViewComponent";
                        }
                        else if (comp.gameObject.GetComponent<ScrollRect>() != null)
                        {
                            listType = "SimpleListViewComponent";
                        }

                        if (listType != null)
                        {
                            listFieldsSb.Append("        private ")
                                .Append(listType)
                                .Append(" m_")
                                .Append(uiItem.Name)
                                .AppendLine("List;");
                        }
                    }

                    // 元素上可关闭点击事件生成（属性仍会生成）
                    if (!uiItem.GenerateClickEvent ||
                        !UIFacadeCodeTemplateLoader.TryGetInteractTemplateId(typeShortName, typeFullName, out string templateId))
                        continue;

                    if (!interactRawById.TryGetValue(templateId, out (string bindRaw, string eventRaw) rawPair))
                    {
                        if (!UIFacadeCodeTemplateLoader.TryLoadInteractTemplate(templateId, out string br, out string er, out string loadErr))
                        {
                            error = loadErr;
                            return false;
                        }

                        rawPair = (br, er);
                        interactRawById[templateId] = rawPair;
                    }

                    string clickMethodName = "On" + uiItem.Name + "Click";
                    string bindBlock = UIFacadeCodeTemplateLoader.ApplyVariables(rawPair.bindRaw,
                        ("TypeFullName", typeFullName),
                        ("TypeShortName", typeShortName),
                        ("FieldName", uiItem.Name),
                        ("Index", i.ToString()),
                        ("ClickMethodName", clickMethodName));
                    AppendSnippetBlock(bindSb, bindBlock);

                    buttonInfos.Add(new ButtonGenInfo(uiItem.Name, typeShortName, typeFullName, i, templateId));
                }
            }

            propertiesCode = propertiesSb.ToString();
            listFieldsCode = listFieldsSb.ToString();
            bindClicksCode = bindSb.ToString();
            return true;
        }

        private static bool TryBuildEventHandlersStubs(
            List<ButtonGenInfo> buttonInfos,
            Dictionary<string, (string bindRaw, string eventRaw)> interactRawById,
            out string eventHandlersCode,
            out string error)
        {
            eventHandlersCode = "";
            error = null;
            var sb = new StringBuilder();

            foreach (ButtonGenInfo btn in buttonInfos)
            {
                if (interactRawById == null || !interactRawById.TryGetValue(btn.InteractTemplateId, out (string bindRaw, string eventRaw) raw))
                {
                    error = "内部错误：缺少交互模板缓存 \"" + btn.InteractTemplateId + "\"。";
                    return false;
                }

                string clickMethodName = "On" + btn.FieldName + "Click";
                string block = UIFacadeCodeTemplateLoader.ApplyVariables(raw.eventRaw,
                    ("TypeFullName", btn.TypeFullName),
                    ("TypeShortName", btn.TypeShortName),
                    ("FieldName", btn.FieldName),
                    ("Index", btn.ElementIndex.ToString()),
                    ("ClickMethodName", clickMethodName));
                AppendSnippetBlock(sb, block);
            }

            eventHandlersCode = sb.ToString();
            return true;
        }

        /// <summary>保证片段末尾有换行，便于多块拼接。</summary>
        private static void AppendSnippetBlock(StringBuilder sb, string block)
        {
            if (string.IsNullOrEmpty(block))
                return;

            sb.Append(block);
            if (sb.Length > 0 && sb[sb.Length - 1] != '\n')
                sb.AppendLine();
        }

        private static string BuildAutoGeneratedRegion(string propertiesCode, string listFieldsCode, string bindClicksCode)
        {
            var sb = new StringBuilder();
            sb.AppendLine("        #region UI Components (Auto Generated)");
            if (!string.IsNullOrEmpty(propertiesCode))
                sb.Append(propertiesCode);
            if (!string.IsNullOrEmpty(listFieldsCode))
            {
                sb.AppendLine();
                sb.Append(listFieldsCode);
            }

            sb.AppendLine("        protected override void OnBindFacade()");
            sb.AppendLine("        {");
            if (!string.IsNullOrEmpty(bindClicksCode))
                sb.Append(bindClicksCode);
            sb.AppendLine("        }");
            sb.AppendLine("        #endregion");
            return sb.ToString();
        }

        private static bool TryReplaceAutoGeneratedRegion(string fileContent, string newRegionBlock, out string updated)
        {
            updated = null;
            int start = fileContent.IndexOf(AutoGenRegionMarker, System.StringComparison.Ordinal);
            if (start < 0)
                return false;

            int regionLineStart = GetLineStartIndex(fileContent, start);

            int searchPos = start + AutoGenRegionMarker.Length;
            int depth = 1;
            int i = searchPos;
            while (i < fileContent.Length && depth > 0)
            {
                int nextRegion = fileContent.IndexOf("#region", i, System.StringComparison.Ordinal);
                int nextEnd = fileContent.IndexOf("#endregion", i, System.StringComparison.Ordinal);
                if (nextEnd < 0)
                    return false;

                if (nextRegion >= 0 && nextRegion < nextEnd)
                {
                    depth++;
                    i = nextRegion + "#region".Length;
                }
                else
                {
                    depth--;
                    if (depth == 0)
                    {
                        int endLineAfterEndRegion = GetLineEndExclusive(fileContent, nextEnd);
                        string before = fileContent.Substring(0, regionLineStart);
                        string after = fileContent.Substring(endLineAfterEndRegion);
                        updated = before + newRegionBlock + after;
                        return true;
                    }

                    i = nextEnd + "#endregion".Length;
                }
            }

            return false;
        }

        /// <summary>
        /// 文件已存在但没有任何自动区域时，尝试把手写类当作 partial 的“主文件”，
        /// 在其类体起始处插入新的自动区域。只有调用方确认文件里没有 OnBindFacade/Facade.Components 时才应调用，
        /// 否则可能产生重复成员。
        /// </summary>
        private static bool TryInsertAutoGeneratedRegion(
            string fileContent,
            string scriptName,
            string baseClass,
            string newRegionBlock,
            out string updated)
        {
            updated = null;
            if (string.IsNullOrEmpty(fileContent) || string.IsNullOrEmpty(newRegionBlock))
            {
                return false;
            }

            // 兼容 "class X : Window" 与 "class X:Window"
            int classIndex = fileContent.IndexOf("class " + scriptName, System.StringComparison.Ordinal);
            if (classIndex < 0)
            {
                return false;
            }

            int braceIndex = fileContent.IndexOf('{', classIndex);
            if (braceIndex < 0)
            {
                return false;
            }

            int classLineEnd = GetLineEndExclusive(fileContent, classIndex);
            if (braceIndex >= classLineEnd && classLineEnd < fileContent.Length)
            {
                // 类声明换行后才出现 {，继续向后找类体的 {
                int nextBrace = fileContent.IndexOf('{', classLineEnd);
                if (nextBrace < 0)
                {
                    return false;
                }

                braceIndex = nextBrace;
            }

            int insertIndex = GetLineEndExclusive(fileContent, braceIndex);
            if (insertIndex < 0)
            {
                return false;
            }

            updated = fileContent.Insert(insertIndex, newRegionBlock);
            return true;
        }

        private static int GetLineStartIndex(string content, int indexInLine)
        {
            int nl = content.LastIndexOf('\n', indexInLine);
            if (nl < 0)
                return 0;
            return nl + 1;
        }

        private static int GetLineEndExclusive(string content, int indexFrom)
        {
            int nl = content.IndexOf('\n', indexFrom);
            if (nl < 0)
                return content.Length;
            return nl + 1;
        }
    }
}
