
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using  NFramework.ModuleSystem;


namespace NFramework.Game.ConfigReader
{
public partial class TbTankMap : IConfig<global::NFramework.Game.TableTankMap>
{
    private System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableTankMap> _dataMap;
    private System.Collections.Generic.List<global::NFramework.Game.TableTankMap> _dataList;

    public void LoadData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableTankMap>(n);
        _dataList = new System.Collections.Generic.List<global::NFramework.Game.TableTankMap>(n);
        for (int i = n; i > 0; --i)
        {
            global::NFramework.Game.TableTankMap _v;
            _v = global::NFramework.Game.TableTankMap.DeserializeTableTankMap(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public static TbTankMap Create() => new TbTankMap();

    // IConfig<T>
    public global::NFramework.Game.TableTankMap Get(int id) => _dataMap[id];
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableTankMap> GetAll() => _dataMap;
    public System.Collections.IDictionary GetDic() => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableTankMap> GetList() => _dataList;
    public global::NFramework.Game.TableTankMap GetBean() => throw new System.NotSupportedException("TbTankMap is a map table, use Get(id).");

    // Convenience helpers
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableTankMap> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableTankMap> DataList => _dataList;
    public global::NFramework.Game.TableTankMap GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public global::NFramework.Game.TableTankMap this[int key] => _dataMap[key];

    public void ResolveRef(TablesReader tables) { }

}

}

