
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using  NFramework.ModuleSystem;


namespace NFramework.Game.ConfigReader
{
public partial class TbUISound : IConfig<global::NFramework.Game.TableUISound>
{
    private System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableUISound> _dataMap;
    private System.Collections.Generic.List<global::NFramework.Game.TableUISound> _dataList;

    public void LoadData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableUISound>(n);
        _dataList = new System.Collections.Generic.List<global::NFramework.Game.TableUISound>(n);
        for (int i = n; i > 0; --i)
        {
            global::NFramework.Game.TableUISound _v;
            _v = global::NFramework.Game.TableUISound.DeserializeTableUISound(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public static TbUISound Create() => new TbUISound();

    // IConfig<T>
    public global::NFramework.Game.TableUISound Get(int id) => _dataMap[id];
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableUISound> GetAll() => _dataMap;
    public System.Collections.IDictionary GetDic() => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableUISound> GetList() => _dataList;
    public global::NFramework.Game.TableUISound GetBean() => throw new System.NotSupportedException("TbUISound is a map table, use Get(id).");

    // Convenience helpers
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableUISound> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableUISound> DataList => _dataList;
    public global::NFramework.Game.TableUISound GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public global::NFramework.Game.TableUISound this[int key] => _dataMap[key];

    public void ResolveRef(TablesReader tables) { }

}

}

