
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace NFramework.Game
{
public sealed partial class TableTankConfig : Luban.BeanBase
{
    public TableTankConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TankBGAsset = _buf.ReadString();
        TankBullet = _buf.ReadInt();
        TankColor = _buf.ReadString();
        TankTargetBricks = _buf.ReadInt();
    }

    public static TableTankConfig DeserializeTableTankConfig(ByteBuf _buf)
    {
        return new TableTankConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 单格位置资源名称
    /// </summary>
    public readonly string TankBGAsset;
    /// <summary>
    /// 坦克子弹
    /// </summary>
    public readonly int TankBullet;
    /// <summary>
    /// 坦克颜色
    /// </summary>
    public readonly string TankColor;
    /// <summary>
    /// 坦克子弹可攻击的目标
    /// </summary>
    public readonly int TankTargetBricks;

    public const int __ID__ = -368790758;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TankBGAsset:" + TankBGAsset + ","
        + "TankBullet:" + TankBullet + ","
        + "TankColor:" + TankColor + ","
        + "TankTargetBricks:" + TankTargetBricks + ","
        + "}";
    }
}
}

