
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace XHFramework.Game
{
public sealed partial class TableMapLevelConfig : Luban.BeanBase
{
    public TableMapLevelConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BackgroundAsset = _buf.ReadString();
        SlotConfig = _buf.ReadInt();
        BricksConfig = _buf.ReadInt();
        TempShotPosition = _buf.ReadInt();
        ConveyorPosition = _buf.ReadInt();
        HeroPosition = _buf.ReadInt();
        FriendHeroPosition = _buf.ReadInt();
        TankConfig = _buf.ReadInt();
        LevelName = _buf.ReadInt();
    }

    public static TableMapLevelConfig DeserializeTableMapLevelConfig(ByteBuf _buf)
    {
        return new TableMapLevelConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡界面背景资源名称
    /// </summary>
    public readonly string BackgroundAsset;
    /// <summary>
    /// 地图格子槽位配置
    /// </summary>
    public readonly int SlotConfig;
    /// <summary>
    /// 地图初始砖块配置
    /// </summary>
    public readonly int BricksConfig;
    /// <summary>
    /// 可临时摆放的炮塔位置
    /// </summary>
    public readonly int TempShotPosition;
    /// <summary>
    /// 传送带初始可摆放的炮塔数量
    /// </summary>
    public readonly int ConveyorPosition;
    /// <summary>
    /// 英雄位置数量
    /// </summary>
    public readonly int HeroPosition;
    /// <summary>
    /// 朋友英雄位置数量
    /// </summary>
    public readonly int FriendHeroPosition;
    /// <summary>
    /// 炮出现初始摆放配置
    /// </summary>
    public readonly int TankConfig;
    /// <summary>
    /// 名称多语言文本
    /// </summary>
    public readonly int LevelName;

    public const int __ID__ = -731269064;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BackgroundAsset:" + BackgroundAsset + ","
        + "SlotConfig:" + SlotConfig + ","
        + "BricksConfig:" + BricksConfig + ","
        + "TempShotPosition:" + TempShotPosition + ","
        + "ConveyorPosition:" + ConveyorPosition + ","
        + "HeroPosition:" + HeroPosition + ","
        + "FriendHeroPosition:" + FriendHeroPosition + ","
        + "TankConfig:" + TankConfig + ","
        + "LevelName:" + LevelName + ","
        + "}";
    }
}
}

