
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace XHFramework.Game
{
public sealed partial class TableSlotConfig : Luban.BeanBase
{
    public TableSlotConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SlotBGAsset = _buf.ReadString();
        SlotScale = _buf.ReadString();
    }

    public static TableSlotConfig DeserializeTableSlotConfig(ByteBuf _buf)
    {
        return new TableSlotConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 单格位置资源名称
    /// </summary>
    public readonly string SlotBGAsset;
    /// <summary>
    /// 格子大小
    /// </summary>
    public readonly string SlotScale;

    public const int __ID__ = -1733998290;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "SlotBGAsset:" + SlotBGAsset + ","
        + "SlotScale:" + SlotScale + ","
        + "}";
    }
}
}

