
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace XHFramework.Game
{
public sealed partial class TableBricksConfig : Luban.BeanBase
{
    public TableBricksConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BricksBGAsset = _buf.ReadString();
        BricksScale = _buf.ReadString();
        BricksColor = _buf.ReadString();
    }

    public static TableBricksConfig DeserializeTableBricksConfig(ByteBuf _buf)
    {
        return new TableBricksConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 单格位置资源名称
    /// </summary>
    public readonly string BricksBGAsset;
    /// <summary>
    /// 格子大小
    /// </summary>
    public readonly string BricksScale;
    /// <summary>
    /// 砖块颜色
    /// </summary>
    public readonly string BricksColor;

    public const int __ID__ = 850171138;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BricksBGAsset:" + BricksBGAsset + ","
        + "BricksScale:" + BricksScale + ","
        + "BricksColor:" + BricksColor + ","
        + "}";
    }
}
}

