
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace NFramework.Game
{
public sealed partial class TableBricksMap : Luban.BeanBase
{
    public TableBricksMap(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); BricksMapRoad = new System.Collections.Generic.List<System.Collections.Generic.List<int>>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Collections.Generic.List<int> _e0;  {int n1 = _buf.ReadSize(); _e0 = new System.Collections.Generic.List<int>(n1);for(var i1 = 0 ; i1 < n1 ; i1++) { int _e1;  _e1 = _buf.ReadInt(); _e0.Add(_e1);}} BricksMapRoad.Add(_e0);}}
    }

    public static TableBricksMap DeserializeTableBricksMap(ByteBuf _buf)
    {
        return new TableBricksMap(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 从上数 第1行
    /// </summary>
    public readonly System.Collections.Generic.List<System.Collections.Generic.List<int>> BricksMapRoad;

    public const int __ID__ = 2101603228;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BricksMapRoad:" + Luban.StringUtil.CollectionToString(BricksMapRoad) + ","
        + "}";
    }
}
}

