
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System;
using System.Collections.Generic;
using NFramework.ModuleSystem;

namespace NFramework.Game.ConfigReader
{
public partial class TablesReader
{
    // -------------------------------------------------------
    // Per-table instance properties (for direct access)
    // -------------------------------------------------------
    public TbBricksConfig TbBricksConfig {get; private set;}
    public TbBricksMap TbBricksMap {get; private set;}
    public TbEntity TbEntity {get; private set;}
    public TbLocalizationText TbLocalizationText {get; private set;}
    public TbMap TbMap {get; private set;}
    public TbMapLevelConfig TbMapLevelConfig {get; private set;}
    public TbMusic TbMusic {get; private set;}
    public TbRole TbRole {get; private set;}
    public TbScene TbScene {get; private set;}
    public TbSlotConfig TbSlotConfig {get; private set;}
    public TbSlotMap TbSlotMap {get; private set;}
    public TbSound TbSound {get; private set;}
    public TbTankConfig TbTankConfig {get; private set;}
    public TbTankMap TbTankMap {get; private set;}
    public TbUISound TbUISound {get; private set;}

    // -------------------------------------------------------
    // Unified registry: data type => (assetName, reader factory)
    //
    //   AssetName : binary file name passed to the resource loader
    //   Create    : returns an empty IConfig ready for LoadData()
    //
    // Usage in ConfigM:
    //   var info   = TablesReader.Registry[typeof(T)];
    //   var reader = info.Create();
    //   reader.LoadData(new ByteBuf(bytes));
    // -------------------------------------------------------
    public sealed class TableInfo
    {
        public readonly string AssetName;
        public readonly Func<IConfig> Create;
        public TableInfo(string assetName, Func<IConfig> create)
        {
            AssetName = assetName;
            Create    = create;
        }
    }

    public static readonly IReadOnlyDictionary<Type, TableInfo> Registry =
        new Dictionary<Type, TableInfo>
        {
            [typeof(global::NFramework.Game.TableBricksConfig)] = new TableInfo("tbbricksconfig", TbBricksConfig.Create),
            [typeof(global::NFramework.Game.TableBricksMap)] = new TableInfo("tbbricksmap", TbBricksMap.Create),
            [typeof(global::NFramework.Game.TableEntity)] = new TableInfo("tbentity", TbEntity.Create),
            [typeof(global::NFramework.Game.TableLocalizationText)] = new TableInfo("tblocalizationtext", TbLocalizationText.Create),
            [typeof(global::NFramework.Game.TableMap)] = new TableInfo("tbmap", TbMap.Create),
            [typeof(global::NFramework.Game.TableMapLevelConfig)] = new TableInfo("tbmaplevelconfig", TbMapLevelConfig.Create),
            [typeof(global::NFramework.Game.TableMusic)] = new TableInfo("tbmusic", TbMusic.Create),
            [typeof(global::NFramework.Game.TableRole)] = new TableInfo("tbrole", TbRole.Create),
            [typeof(global::NFramework.Game.TableScene)] = new TableInfo("tbscene", TbScene.Create),
            [typeof(global::NFramework.Game.TableSlotConfig)] = new TableInfo("tbslotconfig", TbSlotConfig.Create),
            [typeof(global::NFramework.Game.TableSlotMap)] = new TableInfo("tbslotmap", TbSlotMap.Create),
            [typeof(global::NFramework.Game.TableSound)] = new TableInfo("tbsound", TbSound.Create),
            [typeof(global::NFramework.Game.TableTankConfig)] = new TableInfo("tbtankconfig", TbTankConfig.Create),
            [typeof(global::NFramework.Game.TableTankMap)] = new TableInfo("tbtankmap", TbTankMap.Create),
            [typeof(global::NFramework.Game.TableUISound)] = new TableInfo("tbuisound", TbUISound.Create),
        };

    // -------------------------------------------------------
    // Constructor — eager-loads all tables at once
    // -------------------------------------------------------
    public TablesReader(System.Func<string, ByteBuf> loader)
    {
        TbBricksConfig = TbBricksConfig.Create();
        TbBricksConfig.LoadData(loader("tbbricksconfig"));
        TbBricksMap = TbBricksMap.Create();
        TbBricksMap.LoadData(loader("tbbricksmap"));
        TbEntity = TbEntity.Create();
        TbEntity.LoadData(loader("tbentity"));
        TbLocalizationText = TbLocalizationText.Create();
        TbLocalizationText.LoadData(loader("tblocalizationtext"));
        TbMap = TbMap.Create();
        TbMap.LoadData(loader("tbmap"));
        TbMapLevelConfig = TbMapLevelConfig.Create();
        TbMapLevelConfig.LoadData(loader("tbmaplevelconfig"));
        TbMusic = TbMusic.Create();
        TbMusic.LoadData(loader("tbmusic"));
        TbRole = TbRole.Create();
        TbRole.LoadData(loader("tbrole"));
        TbScene = TbScene.Create();
        TbScene.LoadData(loader("tbscene"));
        TbSlotConfig = TbSlotConfig.Create();
        TbSlotConfig.LoadData(loader("tbslotconfig"));
        TbSlotMap = TbSlotMap.Create();
        TbSlotMap.LoadData(loader("tbslotmap"));
        TbSound = TbSound.Create();
        TbSound.LoadData(loader("tbsound"));
        TbTankConfig = TbTankConfig.Create();
        TbTankConfig.LoadData(loader("tbtankconfig"));
        TbTankMap = TbTankMap.Create();
        TbTankMap.LoadData(loader("tbtankmap"));
        TbUISound = TbUISound.Create();
        TbUISound.LoadData(loader("tbuisound"));
        ResolveRef();
    }

    private void ResolveRef()
    {
        TbBricksConfig.ResolveRef(this);
        TbBricksMap.ResolveRef(this);
        TbEntity.ResolveRef(this);
        TbLocalizationText.ResolveRef(this);
        TbMap.ResolveRef(this);
        TbMapLevelConfig.ResolveRef(this);
        TbMusic.ResolveRef(this);
        TbRole.ResolveRef(this);
        TbScene.ResolveRef(this);
        TbSlotConfig.ResolveRef(this);
        TbSlotMap.ResolveRef(this);
        TbSound.ResolveRef(this);
        TbTankConfig.ResolveRef(this);
        TbTankMap.ResolveRef(this);
        TbUISound.ResolveRef(this);
    }
}

}

