
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using  NFramework.ModuleSystem;


namespace XHFramework.Game.ConfigReader
{
public partial class TbScene : IConfig<global::XHFramework.Game.TableScene>
{
    private System.Collections.Generic.Dictionary<int, global::XHFramework.Game.TableScene> _dataMap;
    private System.Collections.Generic.List<global::XHFramework.Game.TableScene> _dataList;

    public void LoadData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, global::XHFramework.Game.TableScene>(n);
        _dataList = new System.Collections.Generic.List<global::XHFramework.Game.TableScene>(n);
        for (int i = n; i > 0; --i)
        {
            global::XHFramework.Game.TableScene _v;
            _v = global::XHFramework.Game.TableScene.DeserializeTableScene(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public static TbScene Create() => new TbScene();

    // IConfig<T>
    public global::XHFramework.Game.TableScene Get(int id) => _dataMap[id];
    public System.Collections.Generic.IReadOnlyDictionary<int, global::XHFramework.Game.TableScene> GetAll() => _dataMap;
    public System.Collections.IDictionary GetDic() => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::XHFramework.Game.TableScene> GetList() => _dataList;
    public global::XHFramework.Game.TableScene GetBean() => throw new System.NotSupportedException("TbScene is a map table, use Get(id).");

    // Convenience helpers
    public System.Collections.Generic.IReadOnlyDictionary<int, global::XHFramework.Game.TableScene> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::XHFramework.Game.TableScene> DataList => _dataList;
    public global::XHFramework.Game.TableScene GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public global::XHFramework.Game.TableScene this[int key] => _dataMap[key];

    public void ResolveRef(TablesReader tables) { }

}

}

