
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using NFramework.ModuleSystem;


namespace XHFramework.Game.ConfigReader
{
public partial class TbSlotMap : IConfig<global::XHFramework.Game.TableSlotMap>
{
    private System.Collections.Generic.Dictionary<int, global::XHFramework.Game.TableSlotMap> _dataMap;
    private System.Collections.Generic.List<global::XHFramework.Game.TableSlotMap> _dataList;

    public void LoadData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, global::XHFramework.Game.TableSlotMap>(n);
        _dataList = new System.Collections.Generic.List<global::XHFramework.Game.TableSlotMap>(n);
        for (int i = n; i > 0; --i)
        {
            global::XHFramework.Game.TableSlotMap _v;
            _v = global::XHFramework.Game.TableSlotMap.DeserializeTableSlotMap(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public static TbSlotMap Create() => new TbSlotMap();

    // IConfig<T>
    public global::XHFramework.Game.TableSlotMap Get(int id) => _dataMap[id];
    public System.Collections.Generic.IReadOnlyDictionary<int, global::XHFramework.Game.TableSlotMap> GetAll() => _dataMap;
    public System.Collections.IDictionary GetDic() => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::XHFramework.Game.TableSlotMap> GetList() => _dataList;
    public global::XHFramework.Game.TableSlotMap GetBean() => throw new System.NotSupportedException("TbSlotMap is a map table, use Get(id).");

    // Convenience helpers
    public System.Collections.Generic.IReadOnlyDictionary<int, global::XHFramework.Game.TableSlotMap> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::XHFramework.Game.TableSlotMap> DataList => _dataList;
    public global::XHFramework.Game.TableSlotMap GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public global::XHFramework.Game.TableSlotMap this[int key] => _dataMap[key];

    public void ResolveRef(TablesReader tables) { }

}

}

