
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using  NFramework.ModuleSystem;


namespace NFramework.Game.ConfigReader
{
public partial class TbSound : IConfig<global::NFramework.Game.TableSound>
{
    private System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableSound> _dataMap;
    private System.Collections.Generic.List<global::NFramework.Game.TableSound> _dataList;

    public void LoadData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableSound>(n);
        _dataList = new System.Collections.Generic.List<global::NFramework.Game.TableSound>(n);
        for (int i = n; i > 0; --i)
        {
            global::NFramework.Game.TableSound _v;
            _v = global::NFramework.Game.TableSound.DeserializeTableSound(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public static TbSound Create() => new TbSound();

    // IConfig<T>
    public global::NFramework.Game.TableSound Get(int id) => _dataMap[id];
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableSound> GetAll() => _dataMap;
    public System.Collections.IDictionary GetDic() => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableSound> GetList() => _dataList;
    public global::NFramework.Game.TableSound GetBean() => throw new System.NotSupportedException("TbSound is a map table, use Get(id).");

    // Convenience helpers
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableSound> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableSound> DataList => _dataList;
    public global::NFramework.Game.TableSound GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public global::NFramework.Game.TableSound this[int key] => _dataMap[key];

    public void ResolveRef(TablesReader tables) { }

}

}

