
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using  NFramework.ModuleSystem;


namespace NFramework.Game.ConfigReader
{
public partial class TbTankConfig : IConfig<global::NFramework.Game.TableTankConfig>
{
    private System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableTankConfig> _dataMap;
    private System.Collections.Generic.List<global::NFramework.Game.TableTankConfig> _dataList;

    public void LoadData(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, global::NFramework.Game.TableTankConfig>(n);
        _dataList = new System.Collections.Generic.List<global::NFramework.Game.TableTankConfig>(n);
        for (int i = n; i > 0; --i)
        {
            global::NFramework.Game.TableTankConfig _v;
            _v = global::NFramework.Game.TableTankConfig.DeserializeTableTankConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public static TbTankConfig Create() => new TbTankConfig();

    // IConfig<T>
    public global::NFramework.Game.TableTankConfig Get(int id) => _dataMap[id];
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableTankConfig> GetAll() => _dataMap;
    public System.Collections.IDictionary GetDic() => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableTankConfig> GetList() => _dataList;
    public global::NFramework.Game.TableTankConfig GetBean() => throw new System.NotSupportedException("TbTankConfig is a map table, use Get(id).");

    // Convenience helpers
    public System.Collections.Generic.IReadOnlyDictionary<int, global::NFramework.Game.TableTankConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<global::NFramework.Game.TableTankConfig> DataList => _dataList;
    public global::NFramework.Game.TableTankConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public global::NFramework.Game.TableTankConfig this[int key] => _dataMap[key];

    public void ResolveRef(TablesReader tables) { }

}

}

